#+TITLE: Skeletor
#+AUTHOR: Chris Barrett

Skeletor allows you to easily create project templates in Emacs. It comes with a
number of predefined templates and allows you to easily create your own.

* Creating Projects
Use =M-x create-project= to create a new project based on an existing template.
You will be guided through any configuration needed.

By default, new projects are created in =~/Projects=. Customise
=skel-project-directory= to change this.

* Defining Project Templates
There are two simple parts to defining a new project:

1. Create a template directory in the =skel-user-directory=, containing any
   files and directories you'd like
2. Use the =define-project-skeleton= macro to configure how the project template
   will be created.

Filenames and file contents may contain special tokens that will be expanded
when the project is created. For example, the following file template,

#+begin_example
Title: Secret Plans
Project: __PROJECT-NAME__
Author: __USER-NAME__
#+end_example

could be instantiated as the following:

#+begin_example
Title: Secret Plans
Project: Capture Battle-Cat
Author: Skeletor
#+end_example

The variable =skel-global-replacements= defines the replacements available in
all project templates, and each template may declare its own special replacements.

* Contributing
Yes, please do! More project types are especially welcome. Read over
CONTRIBUTING for guidelines.

* License
See COPYING. Copyright (c) 2013 Chris Barrett.
