(source melpa)

(package-file "__PROJECT-NAME__.el")

(development
 (depends-on "ert")
 (depends-on "flycheck")
 (depends-on "flycheck-cask")
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "cask-package-toolset")
 (depends-on "undercover")
 (depends-on "package-lint"))
